### ISSUE TITLE
MongoDBStorage raises exception when connection fails, blocks serialization.

### ISSUE THREAD

**Issue by scottsdevelopment** [idanya/algo-trader#12]
Working on #3 and testing out the #8 changes, the new introduction of username and password raise an Exception while attempting to serialize the loaders. My proposed solution is to use a class decorator such as `@connected` to call `client_connect()` and leave the `client` as `None` during construction. 

Additionally, while the above solution passes, the dependency on `get_aggregated_history` fails further down the chain as a connection dependency is invoked during the `HistoryBucketCompareStrategy` constructor. I'm hesitant to suggest we move the `self.matchers` to a `None` check in `process` but if you have a better idea or thoughts on this issue, please let me know.

I will have a small PR with the above changes to submit shortly.

**Comment by scottsdevelopment** [comment]
If we were to implement a `run` method to `Source` and `Processor` then constructors could hold connection argument objects and run methods could perform the connection by passing these arguments objects.

**Comment by idanya** [comment]
I agree. Connecting to the DB within the constructor is not good practice. 
Everything that happens after the coping of the args to class members can be extracted to a function that will be called before each DB operation to make sure a connection is alive. This could be done via decorator or a simple `_ensureConnection()` private function that will:
1. Connect if no connection has been made.
2. If there is a connection, just return.

**Comment by TheSnowGuru** [comment]
maybe instead of using a database we can use something else like pystore? database are slow and this framework is lightweight and can r/w as well.

**Comment by idanya** [comment]
@TheSnowGuru  I'm not familiar with this specific lib but, yes, it's possible. A new Source/Processor that uses a different storage layer can be beneficial. The storage layer is abstracted from the pipeline itself, so as long as it answers the external interfaces it is valid.
