### ISSUE TITLE
Incorrect sign on cash transaction when closing short trade

### ISSUE THREAD

**Issue by ChrisAnstey** [idanya/algo-trader#5]
Closing a short trade currently results in you gaining the absolute cash value of the position in signals executor.

See [here](https://github.com/idanya/algo-trader/blob/main/src/trade/simple_sum_signals_executor.py#L27):

```
    if self.position[candle.symbol] > 0:
        self.cash += candle.close * self.position[candle.symbol]
    else:
        self.cash -= candle.close * self.position[candle.symbol]
```
When `self.position[candle.symbol]` is positive, i.e. a long position, it makes total sense for cash to increase by the positive value of closing price * position. But when position is negative, i.e. a short, we currently subtract the negative result of closing price * position, which results in an increase to cash.

I'm happy to do a fix, with a test and create a PR.

**Comment by idanya** [comment]
Sounds legit.

Please go over [CONTRIBUTING.md](https://github.com/idanya/algo-trader/blob/main/CONTRIBUTING.md) before making a PR. 

Thank you!
