### ISSUE TITLE
Community discussion

### ISSUE THREAD

**Issue by scottsdevelopment** [idanya/algo-trader#9]
Hi is there any place like Telegram or Discord in which we can discuss the project? I would like to contribute but I also would like to get some of the thoughts of the contributors before doing so.

**Comment by idanya** [comment]
Hi,
There is no official channel right now. However, you could go over the [CONTRIBUTING.md](https://github.com/idanya/algo-trader/blob/main/CONTRIBUTING.md) page and open an issue for whatever subject/bug/feature you'd like to discuss and/or report.

**Comment by scottsdevelopment** [comment]
Ok in the future we could create some community channels, I will close this for now.
